# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "SHOWS" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"hummingbird_id" VARCHAR NOT NULL,"tvdb_id" VARCHAR NOT NULL);

# --- !Downs

drop table "SHOWS";

