web:
  build: .
  volumes:
    - .:/app
  ports:
    - "80:3000"
  restart: always
  container_name: mizuchi-web
db:
  image: postgres:9.4
  ports:
    - "5432:5432"
  container_name: mizuchi-db
  restart: always
  environment:
    - POSTGRES_PASSWORD=root
