# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45ee0048201bb0c29f92b7af2f25f637e3d4fda4d4685c91b5a9189178938240174ed76b03e0e625e9bb95752120aa5ff07828bef5293178969f149bcf6bb3f2

test:
  secret_key_base: 01bdd71c25e26b480672a7245caf5c94f98f0b37008e2a57c3d57f99f807d0ddd68a80c6519db0d63e39385509f908d91b9443f376883208bd719ba264468fc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
